language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install flake8
# command to run tests
script:
  - flake8 --ignore E712,F405,F403,E501 inv/
  - flake8 --ignore E712,F405,F403,E501
